# 日志目录和BUG关键词，path为绝对路径
fil:
  url: 'https://api.node.glif.io/rpc/v0'
  debug: false
  account: 'f02246008'
  msg_server: 'ws://127.0.0.1:8083/echo'
  sectors: '/Users/ym/sectors.txt'
logfile:
  - api: 'api/public/UploadImage'
    path: '/Users/ym/mm.log'
    keyword: ['上传成功','上传失败']
lotus:
  nodes: ['','']

# 定时任务配置
cron:
  sectors_expire: '0 3 * * *'    # 扇区过期信息检查，每天3点运行一次

